# Generated by Django 6.0.4 on 2026-05-06 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='event_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
